#!/bin/bash
# mise description="Generate Swift code of the Open API specification."

set -e

swift-openapi-generator generate \
  --config $MISE_PROJECT_ROOT/Sources/JellyfinAPI/openapi-generator-config.yaml \
  $MISE_PROJECT_ROOT/Sources/JellyfinAPI/openapi.json \
  --output-directory $MISE_PROJECT_ROOT/Sources/JellyfinAPI/OpenAPI
